from typing import List, Optional
from pydantic import BaseModel, Field

class ChangePlan(BaseModel):
    """
    Structured change plan generated by the agent before modifying workspace code.
    """
    goal: str = Field(..., description="High-level goal of the workspace changes")
    reason: str = Field(..., description="Rationale for the proposed modifications")
    files_to_modify: List[str] = Field(default_factory=list, description="List of relative file paths to modify")
    files_to_add: List[str] = Field(default_factory=list, description="List of new relative file paths to create")
    validation_steps: List[str] = Field(default_factory=list, description="Deterministic verification steps to ensure code quality")
    risk_level: str = Field(default="LOW", description="Risk assessment: LOW, MEDIUM, or HIGH")
