from abc import ABC, abstractmethod
from typing import List
from app.services.agent.models import AgentState, AgentAction

class BasePlanner(ABC):
    """
    Abstract Planner interface for DevOnCall Agent Runtime.
    Decouples reasoning & next-action selection from specific LLM vendors.
    """

    @abstractmethod
    def plan(self, state: AgentState, available_tools: List[str]) -> AgentAction:
        """
        Given the current AgentState and list of allowed tool names, determine the next AgentAction.
        Must NOT directly execute tools.
        """
        pass


class MockPlanner(BasePlanner):
    """
    Deterministic Mock Planner for testing and demonstration without real LLM credentials.
    Executes predictable multi-step tool call plans based on the user's task.
    """

    def plan(self, state: AgentState, available_tools: List[str]) -> AgentAction:
        task_lower = state.user_task.lower()
        step = state.current_step
        approved = state.run_context.get("approved", False)
        default_branch = state.run_context.get("default_branch", "main")

        # Check for Coding & Validation Task keywords
        is_sandbox_task = any(kw in task_lower for kw in ["sandbox", "validate", "verify"])
        is_coding_task = any(kw in task_lower for kw in ["fix", "code", "modify", "change", "create", "bug", "feature", "update", "hello", "greeting", "add"])

        if is_sandbox_task and is_coding_task:
            if step == 0 and "repository_info" in available_tools:
                return AgentAction(action_type="tool_call", tool="repository_info", input={}, summary="Fetch repository identity and metadata.")
            elif step == 1 and "search_repository" in available_tools:
                return AgentAction(action_type="tool_call", tool="search_repository", input={"query": "hello"}, summary="Search repository for target code pattern.")
            elif step == 2 and "read_file" in available_tools:
                return AgentAction(action_type="tool_call", tool="read_file", input={"path": "hello.py"}, summary="Read source file contents before modification.")
            elif step == 3 and "create_workspace" in available_tools:
                return AgentAction(action_type="tool_call", tool="create_workspace", input={"base_branch": default_branch}, summary=f"Create isolated workspace and checkout feature branch from {default_branch}.")
            elif step == 4 and "write_file" in available_tools:
                return AgentAction(action_type="tool_call", tool="write_file", input={"path": "hello.py", "content": "# DevOnCall Agent Fix\ndef hello():\n    return 'Hello DevOnCall!'\n"}, summary="Apply requested code modification in isolated workspace.")
            elif step == 5 and "sandbox_validate" in available_tools:
                return AgentAction(action_type="tool_call", tool="sandbox_validate", input={"workspace_id": state.run_context.get("workspace_id", f"ws-{state.run_id[:8]}"), "command_type": "TEST", "force_mock": True}, summary="Run controlled sandbox validation suite for workspace modification.")
            elif step == 6 and "git_diff" in available_tools:
                return AgentAction(action_type="tool_call", tool="git_diff", input={}, summary="Generate unified diff of workspace modifications.")
            elif step == 7 and "git_commit" in available_tools:
                return AgentAction(action_type="tool_call", tool="git_commit", input={"message": "Fix: update hello greeting function", "base_branch": default_branch}, summary="Stage workspace changes and create commit on feature branch.")
            elif step == 8 and not approved:
                return AgentAction(action_type="await_approval", summary="Workspace changes committed to feature branch. Awaiting human approval before Pull Request creation.", completed=False)
            elif step == 8 and approved:
                if "create_pull_request" in available_tools:
                    return AgentAction(action_type="tool_call", tool="create_pull_request", input={"approved": True, "base_branch": default_branch, "title": f"DevOnCall Agent Fix: {state.user_task[:40]}", "body": "Automated workspace fix generated by DevOnCall coding agent."}, summary=f"Create Pull Request targeting default {default_branch} branch after human approval.")
            return AgentAction(action_type="complete", summary="Coding task investigation, workspace changes, sandbox validation, and Pull Request creation finished successfully.", completed=True)

        if is_coding_task:
            if step == 0 and "repository_info" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="repository_info",
                    input={},
                    summary="Fetch repository identity and metadata."
                )
            elif step == 1 and "search_repository" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="search_repository",
                    input={"query": "hello"},
                    summary="Search repository for target code pattern."
                )
            elif step == 2 and "read_file" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="read_file",
                    input={"path": "hello.py"},
                    summary="Read source file contents before modification."
                )
            elif step == 3 and "create_workspace" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="create_workspace",
                    input={"base_branch": default_branch},
                    summary=f"Create isolated workspace and checkout feature branch from {default_branch}."
                )
            elif step == 4 and "write_file" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="write_file",
                    input={
                        "path": "hello.py",
                        "content": "# DevOnCall Agent Fix\ndef hello():\n    return 'Hello DevOnCall!'\n"
                    },
                    summary="Apply requested code modification in isolated workspace."
                )
            elif step == 5 and "git_diff" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="git_diff",
                    input={},
                    summary="Generate unified diff of workspace modifications."
                )
            elif step == 6 and "git_commit" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="git_commit",
                    input={"message": "Fix: update hello greeting function", "base_branch": default_branch},
                    summary="Stage workspace changes and create commit on feature branch."
                )
            elif step == 7 and not approved:
                return AgentAction(
                    action_type="await_approval",
                    summary="Workspace changes committed to feature branch. Awaiting human approval before Pull Request creation.",
                    completed=False
                )
            elif step == 7 and approved:
                if "create_pull_request" in available_tools:
                    return AgentAction(
                        action_type="tool_call",
                        tool="create_pull_request",
                        input={
                            "approved": True,
                            "base_branch": default_branch,
                            "title": f"DevOnCall Agent Fix: {state.user_task[:40]}",
                            "body": "Automated workspace fix generated by DevOnCall coding agent."
                        },
                        summary=f"Create Pull Request targeting default {default_branch} branch after human approval."
                    )
            return AgentAction(
                action_type="complete",
                summary="Coding task investigation, workspace changes, and Pull Request creation finished successfully.",
                completed=True
            )

        # Plan Sequence for "structure" tasks
        if "structure" in task_lower and "understand" not in task_lower:
            if step == 0 and "repository_tree" in available_tools:
                return AgentAction(
                    action_type="tool_call",
                    tool="repository_tree",
                    input={"max_depth": 3},
                    summary="Inspect top-level repository tree hierarchy."
                )
            return AgentAction(
                action_type="complete",
                summary="Repository structure investigation completed successfully.",
                completed=True
            )

        # Default Multi-step Read-only Investigation Sequence
        if step == 0 and "repository_info" in available_tools:
            return AgentAction(
                action_type="tool_call",
                tool="repository_info",
                input={},
                summary="Fetch repository identity, default branch, languages, and file statistics."
            )
        elif step == 1 and "repository_tree" in available_tools:
            return AgentAction(
                action_type="tool_call",
                tool="repository_tree",
                input={"max_depth": 3},
                summary="Inspect normalized repository tree hierarchy."
            )
        elif step == 2 and "project_snapshot" in available_tools:
            return AgentAction(
                action_type="tool_call",
                tool="project_snapshot",
                input={},
                summary="Retrieve structural RepositorySnapshot payload."
            )

        # Default completion action when steps exhaust or tools complete
        return AgentAction(
            action_type="complete",
            summary="Comprehensive repository analysis and tool execution finished.",
            completed=True
        )


class MockRepairPlanner(BasePlanner):
    """
    Mock Repair Planner for Phase 6 Bounded Self-Correction testing scenarios (A, B, C, D, E).
    """

    def __init__(self, scenario: str = "SCENARIO_A"):
        self.scenario = scenario

    def plan(self, state: AgentState, available_tools: List[str]) -> AgentAction:
        step = state.current_step

        if self.scenario == "SCENARIO_A":
            if step == 0:
                return AgentAction(
                    action_type="tool_call",
                    tool="sandbox_validate",
                    input={"workspace_id": "ws-1", "command_type": "TEST", "force_mock": True},
                    summary="Run initial validation (expecting FAIL)."
                )
            elif step == 1:
                return AgentAction(
                    action_type="tool_call",
                    tool="write_file",
                    input={"path": "app.py", "content": "# Fixed bug\ndef app(): return True\n"},
                    summary="Apply fix for identified test failure."
                )
            elif step == 2:
                return AgentAction(
                    action_type="tool_call",
                    tool="sandbox_validate",
                    input={"workspace_id": "ws-1", "command_type": "TEST", "force_mock": True},
                    summary="Re-run validation (expecting PASS)."
                )
            elif step == 3 and not state.run_context.get("approved"):
                return AgentAction(
                    action_type="await_approval",
                    summary="Validation passed. Awaiting human approval before PR.",
                    completed=False
                )
            else:
                return AgentAction(action_type="complete", summary="Scenario A finished successfully.", completed=True)

        if self.scenario == "SCENARIO_B":
            if step < 2:
                return AgentAction(
                    action_type="tool_call",
                    tool="sandbox_validate",
                    input={"workspace_id": "ws-FAIL", "command_type": "TEST", "force_mock": True},
                    summary="Run validation (repeating failure)."
                )
            return AgentAction(
                action_type="await_approval",
                summary="Repeated failure threshold reached. Flagging for human review.",
                completed=False
            )

        if self.scenario == "SCENARIO_C":
            return AgentAction(
                action_type="complete",
                summary="Sandbox BLOCKED. Stopping agent execution.",
                completed=True
            )

        if self.scenario == "SCENARIO_D":
            if step == 0:
                return AgentAction(
                    action_type="tool_call",
                    tool="sandbox_validate",
                    input={"workspace_id": "ws-1", "command_type": "TYPECHECK", "force_mock": True},
                    summary="Run TYPECHECK validation."
                )
            elif step == 1:
                return AgentAction(
                    action_type="tool_call",
                    tool="write_file",
                    input={"path": "src/index.ts", "content": "const x: string = 'fixed';\n"},
                    summary="Fix TypeScript type error."
                )
            elif step == 2:
                return AgentAction(
                    action_type="tool_call",
                    tool="sandbox_validate",
                    input={"workspace_id": "ws-1", "command_type": "TEST", "force_mock": True},
                    summary="Run TEST validation after typecheck pass."
                )
            else:
                return AgentAction(action_type="complete", summary="Scenario D finished successfully.", completed=True)

        return MockPlanner().plan(state, available_tools)


class LLMPlanner(BasePlanner):
    """
    Boundary stub for future LLM-based planner engines.
    """

    def plan(self, state: AgentState, available_tools: List[str]) -> AgentAction:
        return MockPlanner().plan(state, available_tools)
